### ISSUE TITLE
Allow configuration of installation page via meta-data (front-matter)

### ISSUE THREAD

**Issue by froschdesign** [laminas/documentation-theme#77]
Currently, the automatic generation of the installation page is configured via the MkDocs configuration file (`mkdocs.yml`) but it would be more intuitive to insert this directly into the related file.

## Current Usage

`mkdocs.yml`

```yaml
extra:
    project: Components
    installation:
        config_provider_class: 'Laminas\Cache\ConfigProvider'
        module_class: 'Laminas\Cache\Module'
```

https://github.com/laminas/laminas-cache/blob/070f1942d031abb8ce976e3cfdbd74a2674655c8/mkdocs.yml#L40-L44

## Preferred Usage

`installation.md`:

```markdown
---
config_provider_class: Laminas\Cache\ConfigProvider
module_class: Laminas\Cache\Module
---

# This Is Only a Placeholder

The content of this page can be found under:

https://github.com/laminas/documentation-theme/blob/master/theme/pages/installation.html
```

https://www.mkdocs.org/user-guide/writing-your-docs/#meta-data
